package hibernate;
// Generated 12-abr-2020 0:01:43 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Clientes generated by hbm2java
 */
public class Clientes  implements java.io.Serializable {


     private Integer codigo;
     private Estado estado;
     private String nombreCliente;
     private String ruc;
     private String nombreContacto;
     private String email;
     private String telefono;
     private String usuarioCreador;
     private Date fechaCreacion;
     private String usuarioModificador;
     private Date fechaModificacion;

    public Clientes() {
    }

	
    public Clientes(Estado estado, String nombreCliente, String ruc, String nombreContacto, String email, String telefono, String usuarioCreador, Date fechaCreacion) {
        this.estado = estado;
        this.nombreCliente = nombreCliente;
        this.ruc = ruc;
        this.nombreContacto = nombreContacto;
        this.email = email;
        this.telefono = telefono;
        this.usuarioCreador = usuarioCreador;
        this.fechaCreacion = fechaCreacion;
    }
    public Clientes(Estado estado, String nombreCliente, String ruc, String nombreContacto, String email, String telefono, String usuarioCreador, Date fechaCreacion, String usuarioModificador, Date fechaModificacion) {
       this.estado = estado;
       this.nombreCliente = nombreCliente;
       this.ruc = ruc;
       this.nombreContacto = nombreContacto;
       this.email = email;
       this.telefono = telefono;
       this.usuarioCreador = usuarioCreador;
       this.fechaCreacion = fechaCreacion;
       this.usuarioModificador = usuarioModificador;
       this.fechaModificacion = fechaModificacion;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public String getNombreCliente() {
        return this.nombreCliente;
    }
    
    public void setNombreCliente(String nombreCliente) {
        this.nombreCliente = nombreCliente;
    }
    public String getRuc() {
        return this.ruc;
    }
    
    public void setRuc(String ruc) {
        this.ruc = ruc;
    }
    public String getNombreContacto() {
        return this.nombreContacto;
    }
    
    public void setNombreContacto(String nombreContacto) {
        this.nombreContacto = nombreContacto;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getUsuarioCreador() {
        return this.usuarioCreador;
    }
    
    public void setUsuarioCreador(String usuarioCreador) {
        this.usuarioCreador = usuarioCreador;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getUsuarioModificador() {
        return this.usuarioModificador;
    }
    
    public void setUsuarioModificador(String usuarioModificador) {
        this.usuarioModificador = usuarioModificador;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


